make parameter_write idempotent
cloudposse/terraform-aws-ssm-parameter-store pull request #17
Opened 2020-10-15 21:46 UTC by dennybaa

2020-10-27 20:26 UTC, Gowiem commented
/test all

2020-10-27 20:31 UTC, Gowiem requested changes
@dennybaa This is looking good. One requested change and a question. 

Also, can you provide the reasoning for this PR in your PR description?

2020-10-27 20:31 UTC, Gowiem commented on main.tf
> +  description     = each.value.description
The default for the description previously was the provided name. Did you purposefully remove that from your `parameter_write_defaults` or was that unintentional?

2020-10-27 20:31 UTC, Gowiem commented on versions.tf
> +  required_version = ">= 0.12.6, < 0.14"
Our standard pinning nowadays is to only pin the lower bound. Can you update this and the below `required_providers` block to only pin the `>= XX` value and don't include the upper bounds?

2020-12-25 07:07 UTC, dennybaa commented on main.tf
> +  description     = each.value.description
Well, I think yes. Since there's 0% in the description same as name

2021-02-17 16:20 UTC, closed without merging