make parameter_write idempotent
cloudposse/terraform-aws-ssm-parameter-store pull request #27
Opened 2021-02-17 16:19 UTC by dennybaa

https://github.com/cloudposse/terraform-aws-ssm-parameter-store/pull/17

2021-02-17 16:22 UTC, dennybaa commented
/test all

2021-02-17 18:06 UTC, maximmi commented
/test all

2021-02-18 13:21 UTC, dennybaa commented
CI fails:
```
[contrib-1 81fd85f] Auto Format
 2 files changed, 28 insertions(+), 2 deletions(-)
+ [[ dennybaa == \c\l\o\u\d\p\o\s\s\e\b\o\t ]]
+ git push
remote: Permission to dysnix/terraform-aws-ssm-parameter-store.git denied to cloudpossebot.
fatal: unable to access 'https://github.com/dysnix/terraform-aws-ssm-parameter-store/': The requested URL returned error: 403
Error: Process completed with exit code 128.
```

2021-02-22 21:14 UTC, osterman commented
/test all

2021-02-22 21:15 UTC, osterman commented
/rebuild-readme

2021-03-01 17:21 UTC, SweetOps requested changes

2021-03-01 17:21 UTC, SweetOps commented on main.tf
> +  parameter_write = var.enabled ? { for e in var.parameter_write : e.name => merge(var.parameter_write_defaults, e) } : {}
```suggestion
  parameter_write = module.this.enabled ? { for e in var.parameter_write : e.name => merge(var.parameter_write_defaults, e) } : {}
```

2021-03-01 17:23 UTC, SweetOps commented
dennybaa, LGTM just one nitpick (see requested changes)

> CI fails:

could you run the following commands locally and commit:

```
make init
make readme
terraform fmt
```

2021-03-02 06:53 UTC, dennybaa commented
> dennybaa, LGTM just one nitpick (see requested changes)
> 
> > CI fails:
> 
> could you run the following commands locally and commit:
> 
> ```
> make init
> make readme
> terraform fmt
> ```

np. done

2021-03-04 13:07 UTC, SweetOps commented
/test all

2021-03-04 13:15 UTC, SweetOps requested changes

2021-03-04 13:15 UTC, SweetOps commented on variables.tf
> +  }
description is `required`

2021-03-04 14:15 UTC, dennybaa commented on variables.tf
> +  }
required for ?

2021-03-04 14:22 UTC, dennybaa commented on variables.tf
> +  }
I feel negative about adding the description, just because it was here before. Being obviously an overkill substitution of the name....

```
  description = lookup(
    tolist(var.parameter_write)[count.index],
    "description",
    tolist(var.parameter_write)[count.index]["name"]
  )
```

@SweetOps if you can could explain why it's required I will definitely consider

2021-03-04 14:29 UTC, SweetOps commented on variables.tf
> +  }
1. Write description for inputs/outputs it's just a good practise 
2. It's requirement of CI test

2021-03-04 17:20 UTC, dennybaa commented on variables.tf
> +  }
@SweetOps 
1. Right, but what is the connection to the parameter passed down to the resource. It has nothing to do with inputs/outputs...
2. This is a false positive...

2021-03-04 17:22 UTC, dennybaa commented on variables.tf
> +  }
@SweetOps https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_parameter#description

2021-03-04 17:29 UTC, dennybaa commented on variables.tf
> +  }
@SweetOps oh sorry)) we are about different descriptions, completely missed it out. Will add

2021-03-04 17:38 UTC, SweetOps commented on variables.tf
> +  }
@dennybaa and again need to regenerate `readme`

```
make init
make readme
terraform fmt
```

2021-03-04 17:42 UTC, dennybaa commented on variables.tf
> +  }
yep, already

2021-03-04 17:47 UTC, SweetOps commented
/test readme

2021-03-04 17:51 UTC, SweetOps commented
/test all

2021-03-04 17:57 UTC, SweetOps approved these changes

2021-03-04 17:59 UTC, merged